version: '3.3'
services:
  solr-production:
    image: solr:8.8
    container_name: lametro-production-solr
    volumes:
      - ./solr_configs:/la-metro-councilmatic_configs
      - data:/opt/solr/server/solr/mycores
    command: sh -c 'solr-create -c lametro -d /la-metro-councilmatic_configs'
    ports:
      - '0.0.0.0:8985:8983'
    environment:
      - SOLR_LOG_LEVEL=ERROR
      - SOLR_HEAP=1g
    restart: on-failure
  solr-staging:
    image: solr:8.8
    container_name: lametro-staging-solr
    volumes:
      - ./solr_configs:/la-metro-councilmatic_configs
      - data:/opt/solr/server/solr/mycores
    command: sh -c 'solr-create -c lametro-staging -d /la-metro-councilmatic_configs'
    ports:
      - '0.0.0.0:8986:8983'
    environment:
      SOLR_LOG_LEVEL: ERROR
    restart: on-failure
  # TODO: Remove post upgrade
  solr-upgrade:
    image: solr:8.8
    container_name: lametro-staging-solr
    volumes:
      - ./solr_configs:/la-metro-councilmatic_configs
      - data:/opt/solr/server/solr/mycores
    command: sh -c 'solr-create -c lametro-staging -d /la-metro-councilmatic_configs'
    ports:
      - '0.0.0.0:8986:8983'
    environment:
      SOLR_LOG_LEVEL: ERROR
    restart: on-failure
volumes:
  data:
