FROM ghcr.io/datamade/la-metro-councilmatic:master

COPY ./requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt --use-deprecated=legacy-resolver
