version: '2.4'

services:
  locust:
    container_name: lametro-locust
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    ports:
      - 8089:8089
    command: locust
