---
title: "lametro.CommitteeDisplaySettings"
date: 2026-06-04
date-modified: last-modified
---


## Model Info

| Key | Value |
|---|-----|
| Model Name | CommitteeDisplaySettings |
| Verbose Name | committee display settings |
| Verbose Name Plural | committee display settingss |
| Docstring | <p>Allowlist of committees to display on the website. Committees are sourced<br>from scraper data; admins select which ones to surface. If no committees<br>are selected, the site falls back to showing all committees with current<br>members.</p> |
| Is Abstract | False |
| Is Proxy | False |
| Is Managed | True |
| Ordering | [] |
| Permissions | [] |
| Default Permissions | ('add', 'change', 'delete', 'view') |
| Indexes | [] |
| Constraints | [] |
| Database Table | lametro_committeedisplaysettings |
| Base Manager | None |
| Default Manager | None |
| File | /app/lametro/models/cms.py |
| Starting Line Number | 401 |
| Method Resolution Order | (<class 'lametro.models.cms.CommitteeDisplaySettings'>, <class 'wagtail.contrib.settings.models.BaseGenericSetting'>, <class 'wagtail.contrib.settings.models.AbstractSetting'>, <class 'django.db.models.base.Model'>, <class 'object'>) |

## Fields

| Field Name | Field Type | Database Column | Database Type | Verbose Name |
|----------|----------|---------------|-------------|------------|
| `CommitteeDisplaySettings_hidden_committees+` | ManyToOneRel |  | integer |  |
| `hidden_committees` | ManyToManyField | hidden_committees | through lametro.CommitteeDisplaySettings_hidden_committees | hidden committees |
| `id (pk)` | AutoField | id | serial | ID |

## Relations

| Field Name | Field Type | Database Column | Database Type | Related Model | Related Name |
|----------|----------|---------------|-------------|-------------|------------|
| `hidden_committees` | ManyToManyField | hidden_committees | through lametro.CommitteeDisplaySettings_hidden_committees | lametro.LAMetroOrganization | _lametro_committeedisplaysettings_hidden_committees_+ |

fields_reverse_relation=[FieldReverseRelation(name='CommitteeDisplaySettings_hidden_committees+ (no reverse relation allowed)', field_type='ManyToOneRel', field_db_type='integer', related_model='lametro.CommitteeDisplaySettings_hidden_committees', field_name_on_related_model='committeedisplaysettings', field_type_on_related_model='ForeignKey')]

## Reverse Relations

| Field Name | Field Type | Database Type | Related Model | Field Name on Related Model | Field Type on Related Model |
|----------|----------|-------------|-------------|---------------------------|---------------------------|
| `CommitteeDisplaySettings_hidden_committees+ (no reverse relation allowed)` | ManyToOneRel | integer | lametro.CommitteeDisplaySettings_hidden_committees | committeedisplaysettings | ForeignKey |

## Methods

### Other Methods

| Method Name | Signature | Docstring | File | Line Number |
|-----------|---------|---------|----|-----------|
| `base_form_class` | `(*args, **kwargs)` | <p>The main implementation of all the Form logic. Note that this class is<br>different than Form. See the comments by the Form class for more info. Any<br>improvements to the form API should be made to this class, not to the Form<br>class.</p> | /app/lametro/wagtail_hooks.py | 328 |
| `base_queryset` | `()` | <p>Returns a queryset of objects of this type to use as a base.</p><p>You can use the `select\_related` attribute on your class to<br>specify a list of foreign key field names, which the method<br>will attempt to select additional related-object data for<br>when the query is executed.</p><p>If your needs are more complex than this, you can override<br>this method on your custom class.</p> | python3.10/site-packages/wagtail/contrib/settings/models.py | 30 |
| `get_cache_attr_name` | `()` | <p>Returns the name of the attribute that should be used to store<br>a reference to the fetched/created object on a request.</p> | python3.10/site-packages/wagtail/contrib/settings/models.py | 48 |
| `get_page_url` | `(self, attribute_name, request=None)` | <p>Returns the URL of a page referenced by a foreign key<br>(or other attribute) matching the name ``attribute\_name``.<br>If the field value is null, or links to something other<br>than a ``Page`` object, an empty string is returned.<br>The result is also cached per-object to facilitate<br>fast repeat access.</p><p>Raises an ``AttributeError`` if the object has no such<br>field or attribute.</p> | python3.10/site-packages/wagtail/contrib/settings/models.py | 67 |
| `load` | `(request_or_site=None)` | <p>Get or create an instance of this model. There is only ever one<br>instance of models inheriting from `AbstractSetting` so we can<br>use `pk=1`.</p><p>If `request\_or\_site` is present and is a request object, then we cache<br>the result on the request for faster repeat access.</p> | python3.10/site-packages/wagtail/contrib/settings/models.py | 179 |


### Private Methods

| Method Name | Signature | Docstring | File | Line Number |
|-----------|---------|---------|----|-----------|
| `_get_or_create` | `()` | <p>Internal convenience method to get or create the first instance.</p><p>We cannot hardcode `pk=1`, for example, as not all database backends<br>use sequential IDs (e.g. Postgres).</p> | python3.10/site-packages/wagtail/contrib/settings/models.py | 165 |


### Dunder Methods

| Method Name | Signature | Docstring | File | Line Number |
|-----------|---------|---------|----|-----------|
| `__class__` | `(name, bases, attrs, **kwargs)` | <p>Metaclass for all models.</p> | python3.10/site-packages/django/db/models/base.py | 72 |
| `__delattr__` | `(self, name, /)` | <p>Implement delattr(self, name).</p> |  |  |
| `__dir__` | `(self, /)` | <p>Default dir() implementation.</p> |  |  |
| `__eq__` | `(self, other)` | <p>Return self==value.</p> | python3.10/site-packages/django/db/models/base.py | 526 |
| `__format__` | `(self, format_spec, /)` | <p>Default object formatter.</p> |  |  |
| `__ge__` | `(self, value, /)` | <p>Return self>=value.</p> |  |  |
| `__getattribute__` | `(self, name, /)` | <p>Return getattr(self, name).</p> |  |  |
| `__getstate__` | `(self)` | <p>Hook to allow choosing the attributes to pickle.</p> | python3.10/site-packages/wagtail/contrib/settings/models.py | 99 |
| `__gt__` | `(self, value, /)` | <p>Return self>value.</p> |  |  |
| `__hash__` | `(self)` | <p>Return hash(self).</p> | python3.10/site-packages/django/db/models/base.py | 536 |
| `__init__` | `(self, *args, **kwargs)` | <p>Initialize self.  See help(type(self)) for accurate signature.</p> | python3.10/site-packages/wagtail/contrib/settings/models.py | 56 |
| `__init_subclass__` | `No signature found` | <p>This method is called when a class is subclassed.</p><p>The default implementation does nothing. It may be<br>overridden to extend subclasses.</p> |  |  |
| `__le__` | `(self, value, /)` | <p>Return self<=value.</p> |  |  |
| `__lt__` | `(self, value, /)` | <p>Return self<value.</p> |  |  |
| `__ne__` | `(self, value, /)` | <p>Return self!=value.</p> |  |  |
| `__new__` | `(*args, **kwargs)` | <p>Create and return a new object.  See help(type) for accurate signature.</p> |  |  |
| `__reduce__` | `(self)` | <p>Helper for pickle.</p> | python3.10/site-packages/django/db/models/base.py | 541 |
| `__reduce_ex__` | `(self, protocol, /)` | <p>Helper for pickle.</p> |  |  |
| `__repr__` | `(self)` | <p>Return repr(self).</p> | python3.10/site-packages/django/db/models/base.py | 520 |
| `__setattr__` | `(self, name, value, /)` | <p>Implement setattr(self, name, value).</p> |  |  |
| `__setstate__` | `(self, state)` |  | python3.10/site-packages/django/db/models/base.py | 564 |
| `__sizeof__` | `(self, /)` | <p>Size of object in memory, in bytes.</p> |  |  |
| `__str__` | `(self)` | <p>Return str(self).</p> | /app/lametro/models/cms.py | 428 |
| `__subclasshook__` | `No signature found` | <p>Abstract classes can override this to customize issubclass().</p><p>This is invoked early on by abc.ABCMeta.\_\_subclasscheck\_\_().<br>It should return True, False or NotImplemented.  If it returns<br>NotImplemented, the normal algorithm is used.  Otherwise, it<br>overrides the normal algorithm (and the outcome is cached).</p> |  |  |


### Common Django Methods

| Method Name | Signature | Docstring | File | Line Number |
|-----------|---------|---------|----|-----------|
| `_check_column_name_clashes` | `()` |  | python3.10/site-packages/django/db/models/base.py | 1506 |
| `_check_constraints` | `(databases)` |  | python3.10/site-packages/django/db/models/base.py | 1975 |
| `_check_default_pk` | `()` |  | python3.10/site-packages/django/db/models/base.py | 1311 |
| `_check_field_name_clashes` | `()` | <p>Forbid field shadowing in multi-table inheritance.</p> | python3.10/site-packages/django/db/models/base.py | 1449 |
| `_check_fields` | `(**kwargs)` | <p>Perform all field checks.</p> | python3.10/site-packages/django/db/models/base.py | 1390 |
| `_check_id_field` | `()` | <p>Check if `id` field is a primary key.</p> | python3.10/site-packages/django/db/models/base.py | 1432 |
| `_check_index_together` | `()` | <p>Check the value of "index\_together" option.</p> | python3.10/site-packages/django/db/models/base.py | 1589 |
| `_check_indexes` | `(databases)` | <p>Check fields, names, and conditions of indexes.</p> | python3.10/site-packages/django/db/models/base.py | 1643 |
| `_check_local_fields` | `(fields, option)` |  | python3.10/site-packages/django/db/models/base.py | 1732 |
| `_check_long_column_names` | `(databases)` | <p>Check that any auto-generated column names are shorter than the limits<br>for each database in which the model will be created.</p> | python3.10/site-packages/django/db/models/base.py | 1884 |
| `_check_m2m_through_same_relationship` | `()` | <p>Check if no relationship model is used by more than one m2m field.<br>        </p> | python3.10/site-packages/django/db/models/base.py | 1400 |
| `_check_managers` | `(**kwargs)` | <p>Perform all manager checks.</p> | python3.10/site-packages/django/db/models/base.py | 1382 |
| `_check_model` | `()` |  | python3.10/site-packages/django/db/models/base.py | 1369 |
| `_check_model_name_db_lookup_clashes` | `()` |  | python3.10/site-packages/django/db/models/base.py | 1531 |
| `_check_ordering` | `()` | <p>Check "ordering" option -- is it a list of strings and do all fields<br>exist?</p> | python3.10/site-packages/django/db/models/base.py | 1782 |
| `_check_property_name_related_field_accessor_clashes` | `()` |  | python3.10/site-packages/django/db/models/base.py | 1555 |
| `_check_single_primary_key` | `()` |  | python3.10/site-packages/django/db/models/base.py | 1575 |
| `_check_swappable` | `()` | <p>Check if the swapped model exists.</p> | python3.10/site-packages/django/db/models/base.py | 1342 |
| `_check_unique_together` | `()` | <p>Check the value of "unique\_together" option.</p> | python3.10/site-packages/django/db/models/base.py | 1616 |
| `_do_insert` | `(self, manager, using, fields, returning_fields, raw)` | <p>Do an INSERT. If returning\_fields is defined then this method should<br>return the newly created data for the model.</p> | python3.10/site-packages/django/db/models/base.py | 914 |
| `_do_update` | `(self, base_qs, using, pk_val, values, update_fields, forced_update)` | <p>Try to update the model. Return True if the model was updated (if an<br>update query was done and a matching row was found in the DB).</p> | python3.10/site-packages/django/db/models/base.py | 887 |
| `_get_FIELD_display` | `(self, field)` |  | python3.10/site-packages/django/db/models/base.py | 971 |
| `_get_expr_references` | `(expr)` |  | python3.10/site-packages/django/db/models/base.py | 1959 |
| `_get_next_or_previous_by_FIELD` | `(self, field, is_next, **kwargs)` |  | python3.10/site-packages/django/db/models/base.py | 977 |
| `_get_next_or_previous_in_order` | `(self, is_next)` |  | python3.10/site-packages/django/db/models/base.py | 993 |
| `_get_pk_val` | `(self, meta=None)` |  | python3.10/site-packages/django/db/models/base.py | 586 |
| `_get_unique_checks` | `(self, exclude=None)` | <p>Return a list of checks to perform. Since validate\_unique() could be<br>called from a ModelForm, some fields may have been excluded; we can't<br>perform a unique check on a model that is missing fields involved<br>in that check. Fields that did not validate should also be excluded,<br>but they need to be passed in via the exclude argument.</p> | python3.10/site-packages/django/db/models/base.py | 1038 |
| `_perform_date_checks` | `(self, date_checks)` |  | python3.10/site-packages/django/db/models/base.py | 1141 |
| `_perform_unique_checks` | `(self, unique_checks)` |  | python3.10/site-packages/django/db/models/base.py | 1096 |
| `_prepare_related_fields_for_save` | `(self, operation_name)` |  | python3.10/site-packages/django/db/models/base.py | 924 |
| `_save_parents` | `(self, cls, using, update_fields)` | <p>Save all the parents of cls using values from self.</p> | python3.10/site-packages/django/db/models/base.py | 794 |
| `_save_table` | `(self, raw=False, cls=None, force_insert=False, force_update=False, using=None, update_fields=None)` | <p>Do the heavy-lifting involved in saving. Update or insert the data<br>for a single table.</p> | python3.10/site-packages/django/db/models/base.py | 822 |
| `_set_pk_val` | `(self, value)` |  | python3.10/site-packages/django/db/models/base.py | 590 |
| `check` | `(**kwargs)` |  | python3.10/site-packages/django/db/models/base.py | 1278 |
| `clean` | `(self)` | <p>Hook for doing any extra model-wide validation after clean() has been<br>called on every field by self.clean\_fields. Any ValidationError raised<br>by this method will not be associated with a particular field; it will<br>have a special-case association with the field defined by NON\_FIELD\_ERRORS.</p> | python3.10/site-packages/django/db/models/base.py | 1013 |
| `clean_fields` | `(self, exclude=None)` | <p>Clean all fields and raise a ValidationError containing a dict<br>of all validation errors if any occur.</p> | python3.10/site-packages/django/db/models/base.py | 1253 |
| `date_error_message` | `(self, lookup_type, field_name, unique_for)` |  | python3.10/site-packages/django/db/models/base.py | 1170 |
| `delete` | `(self, using=None, keep_parents=False)` |  | python3.10/site-packages/django/db/models/base.py | 958 |
| `from_db` | `(db, field_names, values)` |  | python3.10/site-packages/django/db/models/base.py | 507 |
| `full_clean` | `(self, exclude=None, validate_unique=True)` | <p>Call clean\_fields(), clean(), and validate\_unique() on the model.<br>Raise a ValidationError for any errors that occur.</p> | python3.10/site-packages/django/db/models/base.py | 1217 |
| `get_deferred_fields` | `(self)` | <p>Return a set containing names of deferred fields for this instance.</p> | python3.10/site-packages/django/db/models/base.py | 598 |
| `prepare_database_save` | `(self, field)` |  | python3.10/site-packages/django/db/models/base.py | 1008 |
| `refresh_from_db` | `(self, using=None, fields=None)` | <p>Reload field values from the database.</p><p>By default, the reloading happens from the database this instance was<br>loaded from, or by the read router if this instance wasn't loaded from<br>any database. The using parameter will override the default.</p><p>Fields can be used to specify which fields to reload. The fields<br>should be an iterable of field attnames. If fields is None, then<br>all non-deferred fields are reloaded.</p><p>When accessing deferred fields of an instance, the deferred loading<br>of the field will call this method.</p> | python3.10/site-packages/django/db/models/base.py | 607 |
| `save` | `(self, force_insert=False, force_update=False, using=None, update_fields=None)` | <p>Save the current instance. Override this in a subclass if you want to<br>control the saving process.</p><p>The 'force\_insert' and 'force\_update' parameters can be used to insist<br>that the "save" must be an SQL insert or update (or equivalent for<br>non-SQL backends), respectively. Normally, they should not be set.</p> | python3.10/site-packages/django/db/models/base.py | 685 |
| `save_base` | `(self, raw=False, force_insert=False, force_update=False, using=None, update_fields=None)` | <p>Handle the parts of saving which should be done only once per save,<br>yet need to be done in raw saves, too. This includes some sanity<br>checks and signal sending.</p><p>The 'raw' argument is telling save\_base not to save any parent<br>models and not to do any changes to the values before save. This<br>is used by fixture loading.</p> | python3.10/site-packages/django/db/models/base.py | 743 |
| `serializable_value` | `(self, field_name)` | <p>Return the value of the field name for this instance. If the field is<br>a foreign key, return the id value instead of the object. If there's<br>no Field object with this name on the model, return the model<br>attribute's value.</p><p>Used to serialize a field's value (in the serializer, or form output,<br>for example). Normally, you would just access the attribute directly<br>and not use this method.</p> | python3.10/site-packages/django/db/models/base.py | 668 |
| `unique_error_message` | `(self, model_class, unique_check)` |  | python3.10/site-packages/django/db/models/base.py | 1187 |
| `validate_unique` | `(self, exclude=None)` | <p>Check unique constraints on the model and raise ValidationError if any<br>failed.</p> | python3.10/site-packages/django/db/models/base.py | 1022 |


---
