# Generated by Django 2.1.13 on 2019-10-11 17:36

from django.db import migrations, models
import lametro.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('councilmatic_core', '0048_post_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectGuid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LAMetroBill',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('councilmatic_core.bill',),
        ),
        migrations.CreateModel(
            name='LAMetroEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('councilmatic_core.event', lametro.models.LiveMediaMixin),
        ),
        migrations.CreateModel(
            name='LAMetroOrganization',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('councilmatic_core.organization',),
        ),
        migrations.CreateModel(
            name='LAMetroPerson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('councilmatic_core.person',),
        ),
        migrations.CreateModel(
            name='LAMetroPost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('councilmatic_core.post',),
        ),
        migrations.AlterUniqueTogether(
            name='subjectguid',
            unique_together={('guid', 'name')},
        ),
    ]
