# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('councilmatic_core', '0010_auto_20160120_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAMetroBill',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.bill',),
        ),
    ]
