# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0011_auto_20161013_1541'),
        ('lametro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAMetroPost',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.post',),
        ),
    ]
