# Generated by Django 2.2.9 on 2020-01-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lametro', '0002_billpacket_eventagendaitem_eventpacket_eventrelatedentity_membership_relatedbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAMetroSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('guid', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'unique_together': {('guid', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='SubjectGuid',
        ),
    ]
