# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0027_merge'),
        ('lametro', '0002_lametropost'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAMetroPerson',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.person',),
        ),
    ]
