# Generated by Django 2.2.12 on 2020-05-22 18:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lametro', '0003_add_lametro_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='lametrosubject',
            name='classification',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=list, size=None),
        ),
    ]
