# Generated by Django 2.1.14 on 2019-11-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lametro', '0003_eventpacket'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpacket',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventpacket',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
