# Generated by Django 2.2.12 on 2020-06-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lametro', '0004_add_subject_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lametrosubject',
            name='classification',
            field=models.CharField(choices=[('bill_type_exact', 'Board Report Type'), ('lines_and_ways_exact', 'Lines / Ways'), ('phase_exact', 'Phase'), ('project_exact', 'Project'), ('location_exact', 'Location'), ('significant_date_exact', 'Significant Date'), ('motion_by_exact', 'Motion By'), ('topics_exact', 'Subject')], default='topics_exact', max_length=256),
        ),
    ]
