# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-12 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0036_auto_20180302_1247'),
        ('lametro', '0004_lametroevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAMetroOrganization',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.organization',),
        ),
    ]
