# Generated by Django 2.2.16 on 2020-11-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lametro", "0005_add_more_facets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lametrosubject",
            name="classification",
            field=models.CharField(
                choices=[
                    ("bill_type_exact", "Board Report Type"),
                    ("lines_and_ways_exact", "Lines / Ways"),
                    ("phase_exact", "Phase"),
                    ("project_exact", "Project"),
                    ("metro_location_exact", "Metro Location"),
                    (
                        "geo_admin_location_exact",
                        "Geographic / Administrative Location",
                    ),
                    ("significant_date_exact", "Significant Date"),
                    ("motion_by_exact", "Motion By"),
                    ("topics_exact", "Subject"),
                    ("plan_program_policy_exact", "Plan, Program, or Policy"),
                ],
                default="topics_exact",
                max_length=256,
            ),
        ),
    ]
