# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-07 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0041_event_extras'),
        ('lametro', '0005_lametroorganization'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAMetroEventMedia',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('councilmatic_core.eventmedia',),
        ),
    ]
