# Generated by Django 2.2.24 on 2021-11-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lametro', '0006_add_plan_program_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='lametrosubject',
            name='bills',
            field=models.ManyToManyField(related_name='subjects', to='lametro.LAMetroBill'),
        ),
        migrations.RunSQL('''
            INSERT INTO lametro_lametrosubject_bills (
                lametrosubject_id,
                lametrobill_id
            )
            SELECT
                subject.id,
                bill_subjects.id
            FROM (
                SELECT
                    id,
                    UNNEST(subject) AS subject
                FROM opencivicdata_bill
            ) bill_subjects
            JOIN lametro_lametrosubject subject
            ON bill_subjects.subject = subject.name
        ''', reverse_sql='''
            DELETE FROM lametro_lametrosubject_bills
        '''),
    ]
