# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-02 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0044_bill_restrict_view'),
        ('lametro', '0006_lametroeventmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAMetroSubject',
            fields=[
                ('subject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='councilmatic_core.Subject')),
                ('guid', models.CharField(blank=True, max_length=256, null=True)),
            ],
            bases=('councilmatic_core.subject',),
        ),
    ]
