# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-03 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lametro', '0007_lametrosubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='lametrosubject',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lametrosubject',
            name='guid',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
