# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-16 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lametro', '0008_auto_20190503_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectGuid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lametrosubject',
            name='subject_ptr',
        ),
        migrations.DeleteModel(
            name='LAMetroSubject',
        ),
        migrations.AlterUniqueTogether(
            name='subjectguid',
            unique_together=set([('guid', 'name')]),
        ),
    ]
