# Generated by Django 2.2.25 on 2022-03-30 15:34

from datetime import datetime

from django.db import migrations, models
import django.db.models.deletion
import lametro.models


def create_lametro_event(apps, schema_editor):
    Event = apps.get_model('councilmatic_core', 'Event')
    LAMetroEvent = apps.get_model('lametro', 'LAMetroEvent')

    past_events = Event.objects.filter(
        event__start_date__lte=lametro.models.app_timezone.localize(datetime.now()).isoformat()
    ).values_list('event_id')

    for e in Event.objects.all():
        lametro_event = LAMetroEvent(event_ptr_id=e.event_id)

        # If the meeting has already happened, set has_broadcast to True
        if e.event_id in past_events:
            lametro_event.has_broadcast = True

        lametro_event.save_base(raw=True)


def destroy_lametro_event(apps, schema_editor):
    LAMetroEvent = apps.get_model('lametro', 'LAMetroEvent')
    LAMetroEvent.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0052_convert_last_action_date_to_datefield'),
        ('lametro', '0008_add_has_broadcast_to_extras'),
    ]

    operations = [
        migrations.RunSQL(
            'SET CONSTRAINTS ALL IMMEDIATE',
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.DeleteModel(
            name='LAMetroEvent',
        ),
        migrations.CreateModel(
            name='LAMetroEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='councilmatic_core.Event')),
                ('has_broadcast', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('councilmatic_core.event', lametro.models.LiveMediaMixin, lametro.models.SourcesMixin),
        ),
        migrations.RunPython(create_lametro_event, destroy_lametro_event),
        migrations.AlterField(
            model_name='eventpacket',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packet', to='councilmatic_core.Event'),
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'
        ),
    ]
