# Generated by Django 2.2.25 on 2022-03-30 15:34

from django.db import migrations, models
import django.db.models.deletion
import lametro.models

# Create LAMetroEvent for every Councilmatic event
# Add signal to create LAMetroEvent for when Councilmatic event created
def create_lametro_event(apps, schema_editor):
    ...
#    Event = apps.get_model('councilmatic_core', 'Event')
#
#    # Create LAMetroEvent for every Councilmatic Event
#    LAMetroEvent = apps.get_model('lametro', 'LAMetroEvent')
#    LAMetroEvent.objects.bulk_create(
#        [LAMetroEvent(councilmatic_event=e) for e in Event.objects.all()]
#    )
#
#    # Set past events as having been broadcast
#    past_events = LAMetroEvent.objects.filter(
#        start_date__lte=app_timezone.localize(datetime.now()).isoformat()
#    )
#    for event in past_events:
#        event.has_broadcast = True
#    Event.objects.bulk_update(past_events, ['has_broadcast'])


def destroy_lametro_event(apps, schema_editor):
    LAMetroEvent = apps.get_model('lametro', 'LAMetroEvent')
    LAMetroEvent.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0052_convert_last_action_date_to_datefield'),
        ('lametro', '0008_add_has_broadcast_to_extras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LAMetroEvent',
        ),
        migrations.CreateModel(
            name='LAMetroEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='councilmatic_core.Event')),
                ('has_broadcast', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('councilmatic_core.event', lametro.models.LiveMediaMixin, lametro.models.SourcesMixin),
        ),
        migrations.RunPython(create_lametro_event, destroy_lametro_event),
        migrations.AlterField(
            model_name='EventPacket',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packet', to='lametro.LAMetroEvent'),
        ),
    ]
