# Generated by Django 2.2.24 on 2021-11-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lametro', '0008_relatebillsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='lametrosubject',
            name='bill_count',
            field=models.IntegerField(default=0),
        ),
    ]
