# Generated by Django 3.2.14 on 2023-01-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lametro', '0009_addeventbroadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbroadcast',
            name='observed',
            field=models.BooleanField(default=True),
        ),
    ]
