# Generated by Django 2.2.25 on 2023-01-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lametro', '0009_addeventbroadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbroadcast',
            name='observed',
            field=models.BooleanField(default=True),
        ),
    ]
