# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-30 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councilmatic_core', '0044_bill_restrict_view'),
        ('lametro', '0009_auto_20190516_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAMetroAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='councilmatic_core.Action')),
            ],
            bases=('councilmatic_core.action',),
        ),
    ]
