# Generated by Django 3.2.20 on 2023-07-21 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lametro", "0010_alter_eventbroadcast_observed"),
        ("lametro", "0011_relatebillsubject"),
    ]

    operations = []
