# Generated by Django 3.2.23 on 2023-11-29 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lametro", "0012_alert"),
        ("lametro", "0012_merge_20230721_1322"),
    ]

    operations = []
