# Generated by Django 3.2.25 on 2024-05-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0013_merge_0012_alert_0012_merge_20230721_1322"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventbroadcast",
            name="is_manually_live",
            field=models.BooleanField(default=False),
        ),
    ]
