# Generated by Django 3.2.25 on 2024-11-21 19:18

from django.db import migrations
import lametro.blocks
import wagtail.blocks
import wagtail.contrib.typed_table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0015_aboutpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "content",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            ("text", wagtail.blocks.RichTextBlock()),
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(),
                                            ),
                                            (
                                                "table",
                                                wagtail.contrib.typed_table_block.blocks.TypedTableBlock(
                                                    [
                                                        (
                                                            "rich_text",
                                                            wagtail.blocks.RichTextBlock(),
                                                        )
                                                    ]
                                                ),
                                            ),
                                            (
                                                "navigation",
                                                lametro.blocks.NavigationBlock(),
                                            ),
                                            (
                                                "responsive_element",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "breakpoints",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "sm",
                                                                        wagtail.blocks.IntegerBlock(
                                                                            default=1,
                                                                            help_text="Mobile phone",
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "md",
                                                                        wagtail.blocks.IntegerBlock(
                                                                            default=2,
                                                                            help_text="Tablet",
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "lg",
                                                                        wagtail.blocks.IntegerBlock(
                                                                            default=4,
                                                                            help_text="Desktop",
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "content",
                                                            wagtail.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "table",
                                                                        wagtail.contrib.typed_table_block.blocks.TypedTableBlock(
                                                                            [
                                                                                (
                                                                                    "rich_text",
                                                                                    wagtail.blocks.RichTextBlock(),
                                                                                )
                                                                            ]
                                                                        ),
                                                                    )
                                                                ]
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "anchor",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add anchor to enable direct links to this section",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
    ]
