# Generated by Django 3.2.25 on 2024-12-05 21:34

import django.contrib.postgres.fields
from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0017_alter_alert_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventNotice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conditions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("future", "Future"),
                                ("upcoming", "Upcoming"),
                                ("ongoing", "Ongoing"),
                                ("concluded", "Concluded"),
                            ],
                            max_length=255,
                        ),
                        default=["future", "Future"],
                        size=None,
                    ),
                ),
                ("message", wagtail.fields.RichTextField()),
            ],
        ),
    ]
