# Generated by Django 3.2.25 on 2024-12-04 19:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("lametro", "0017_alter_alert_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardOfDirectorsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("search_title", models.CharField(max_length=50)),
                ("search_examples", models.CharField(max_length=150)),
                ("geography_tooltip", wagtail.fields.RichTextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
