# Generated by Django 3.2.25 on 2024-12-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0018_eventnotice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventnotice",
            name="comment_conditions",
        ),
    ]
