# Generated by Django 3.2.25 on 2025-02-28 15:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


def create_calendar(apps, schema_editor):
    calendar_model = apps.get_model("lametro", "FiscalYearCalendar")
    calendar_model.objects.create(title="Fiscal Year 2025 (PDF)")


class Migration(migrations.Migration):

    dependencies = [
        ("wagtaildocs", "0012_uploadeddocument"),
        ("lametro", "0019_boardmemberdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventnotice",
            name="comment_conditions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "accepts_live_comment",
                            "Events that accept public comment before and during the meeting",
                        ),
                        (
                            "accepts_comment",
                            "Events that accept public comment before but not during the meeting",
                        ),
                        (
                            "accepts_no_comment",
                            "Events that do not accept public comment",
                        ),
                    ],
                    max_length=255,
                ),
                default=[
                    "accepts_live_comment",
                    "Events that accept public comment before and during the meeting",
                ],
                size=None,
            ),
        ),
        migrations.CreateModel(
            name="FiscalYearCalendar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_calendar),
    ]
