# Generated by Django 3.2.25 on 2024-12-18 20:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("lametro", "0019_boardmemberpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardmemberpage",
            name="bio",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boardmemberpage",
            name="headshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
