# Generated by Django 3.2.25 on 2024-12-18 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0020_auto_20241218_1251"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardmemberpage",
            name="person",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="lametro.lametroperson",
            ),
            preserve_default=False,
        ),
    ]
