# Generated by Django 3.2.25 on 2025-03-10 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('lametro', '0020_auto_20250228_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='URL to existing agenda PDF', null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_agenda', to='lametro.lametroevent')),
            ],
        ),
    ]
