# Generated by Django 3.2.25 on 2025-03-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0020_auto_20250228_0726"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
