# Generated by Django 3.2.25 on 2025-04-18 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0021_eventagenda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventagenda",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manual_agenda",
                to="lametro.lametroevent",
            ),
        ),
    ]
