# Generated by Django 3.2.25 on 2025-03-21 19:16

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0021_alert_expiration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tooltip",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.CharField(max_length=255, unique=True)),
                ("content", wagtail.fields.RichTextField()),
                ("disabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name="alert",
            options={"ordering": ["pk"]},
        ),
    ]
