# Generated by Django 3.2.25 on 2025-03-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0022_auto_20250321_1216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tooltip",
            name="target",
            field=models.CharField(
                choices=[
                    ("board_report_type", "Board Report Type"),
                    ("fiscal_year", "Fiscal Year"),
                    (
                        "geographic_administrative_location",
                        "Geographic / Administrative Location",
                    ),
                    ("lines_ways", "Lines / Ways"),
                    ("meeting", "Meeting"),
                    ("metro_location", "Metro Location"),
                    ("motion_by", "Motion By"),
                    ("phase", "Phase"),
                    ("plan_program_or_policy", "Plan, Program, or Policy"),
                    ("project", "Project"),
                    ("significant_date", "Significant Date"),
                    ("status", "Status"),
                    ("subject", "Subject"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
