# Generated by Django 3.2.25 on 2025-03-26 20:12

from django.db import migrations, models
import django.db.models.deletion
import lametro.blocks
import wagtail.blocks
import wagtail.contrib.typed_table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("lametro", "0023_alter_tooltip_target"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardPoliciesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "content",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "text",
                                                        wagtail.blocks.RichTextBlock(),
                                                    ),
                                                    (
                                                        "image",
                                                        wagtail.images.blocks.ImageChooserBlock(),
                                                    ),
                                                    (
                                                        "table",
                                                        wagtail.contrib.typed_table_block.blocks.TypedTableBlock(
                                                            [
                                                                (
                                                                    "rich_text",
                                                                    wagtail.blocks.RichTextBlock(),
                                                                )
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "navigation",
                                                        lametro.blocks.NavigationBlock(),
                                                    ),
                                                    (
                                                        "responsive_element",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "breakpoints",
                                                                    wagtail.blocks.StructBlock(
                                                                        [
                                                                            (
                                                                                "sm",
                                                                                wagtail.blocks.IntegerBlock(
                                                                                    default=1,
                                                                                    help_text="Mobile phone",
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "md",
                                                                                wagtail.blocks.IntegerBlock(
                                                                                    default=2,
                                                                                    help_text="Tablet",
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "lg",
                                                                                wagtail.blocks.IntegerBlock(
                                                                                    default=4,
                                                                                    help_text="Desktop",
                                                                                ),
                                                                            ),
                                                                        ]
                                                                    ),
                                                                ),
                                                                (
                                                                    "content",
                                                                    wagtail.blocks.StreamBlock(
                                                                        [
                                                                            (
                                                                                "table",
                                                                                wagtail.contrib.typed_table_block.blocks.TypedTableBlock(
                                                                                    [
                                                                                        (
                                                                                            "rich_text",
                                                                                            wagtail.blocks.RichTextBlock(),
                                                                                        )
                                                                                    ]
                                                                                ),
                                                                            )
                                                                        ]
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "anchor",
                                            wagtail.blocks.CharBlock(
                                                help_text="Add anchor to enable direct links to this section",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "aside",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        ("text", wagtail.blocks.RichTextBlock()),
                                    ]
                                ),
                            ),
                        ],
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
