# Generated by Django 3.2.25 on 2025-05-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0022_alter_eventagenda_event"),
        ("lametro", "0023_alter_tooltip_target"),
    ]

    operations = []
