# Generated by Django 3.2.25 on 2025-05-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0024_boardpoliciespage"),
        ("lametro", "0024_merge_20250506_0904"),
    ]

    operations = []
