# Generated by Django 3.2.25 on 2025-05-14 20:50

from django.db import migrations, models


def create_upcoming_calendar(apps, schema_editor):
    calendar_model = apps.get_model("lametro", "FiscalYearCalendar")

    # Apply type to existing calendar
    current_cal = calendar_model.objects.first()
    current_cal.cal_type = "current"
    current_cal.save(update_fields=["cal_type"])

    # Create upcoming calendar
    calendar_model.objects.create(title="Fiscal Year 2026 (PDF)", cal_type="upcoming")


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0025_merge_0024_boardpoliciespage_0024_merge_20250506_0904"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalyearcalendar",
            name="cal_type",
            field=models.CharField(
                choices=[("current", "Current"), ("upcoming", "Upcoming")],
                max_length=20,
                null=True,
                verbose_name="Calendar Type",
            ),
        ),
        migrations.RunPython(create_upcoming_calendar),
    ]
