# Generated by Django 3.2.25 on 2026-02-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0026_fiscalyearcalendar_cal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardmemberdetails",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="The position that will show up on this person's detail page e.g. Board Member",
                max_length=64,
                null=True,
            ),
        ),
    ]
