# Generated by Django 3.2.25 on 2026-03-02 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0026_fiscalyearcalendar_cal_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("bill", "bill"), ("event", "event")], max_length=32
                    ),
                ),
                (
                    "date_last_sent",
                    models.DateTimeField(
                        help_text="The most recent time this notification was sent."
                    ),
                ),
                (
                    "bill",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification",
                        to="lametro.lametrobill",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification",
                        to="lametro.lametroevent",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="translationnotification",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("bill__isnull", False), ("event__isnull", True)),
                    models.Q(("bill__isnull", True), ("event__isnull", False)),
                    _connector="OR",
                ),
                name="only_one_entity",
            ),
        ),
    ]
