# Generated by Django 3.2.25 on 2026-05-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0028_auto_20260325_0942"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitteeDisplaySettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hidden_committees",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select which committees to hide from the website. If none are selected, all committees with current members are shown.",
                        limit_choices_to={"classification": "committee"},
                        related_name="_lametro_committeedisplaysettings_hidden_committees_+",
                        to="lametro.LAMetroOrganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Committee Display Settings",
                "verbose_name_plural": "Committee Display Settings",
            },
        ),
    ]
