# Generated by Django 3.2.25 on 2026-05-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0029_committeedisplaysettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeedisplaysettings",
            name="hidden_committees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select which committees to hide from the website. Only committees with at least one current member are listed. If none are selected, all committees with current members are shown.",
                limit_choices_to={"classification": "committee"},
                related_name="_lametro_committeedisplaysettings_hidden_committees_+",
                to="lametro.LAMetroOrganization",
            ),
        ),
    ]
