# Generated by Django 3.2.25 on 2026-09-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0030_alter_committeedisplaysettings_hidden_committees"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="committeedisplaysettings",
            options={},
        ),
        migrations.CreateModel(
            name="DeletedEventDisplaySettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_events",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select which deleted events to show on the website.",
                        limit_choices_to={"extras": {"deleted_in_legistar": True}},
                        related_name="_lametro_deletedeventdisplaysettings_deleted_events_+",
                        to="lametro.LAMetroEvent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
