# Generated by Django 3.2.25 on 2026-09-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lametro", "0031_auto_20260929_1426"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deletedeventdisplaysettings",
            name="deleted_events",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select which deleted events to show on the website.",
                related_name="_lametro_deletedeventdisplaysettings_deleted_events_+",
                to="lametro.LAMetroEvent",
            ),
        ),
    ]
