project:
  type: website

website:
  title: "LA Metro Councilmatic Documentation"
  sidebar:
    style: "docked"
    search: true
    contents: auto
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/Metro-Records/la-metro-councilmatic
          - text: Issue Tracker
            href: https://github.com/Metro-Records/la-metro-councilmatic/issues

format:
  html:
    theme: litera
    css: styles.css
    toc: true
